# -*- coding: utf-8 -*-
"""run_telegram_bot Mutiara Bangsa.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bUad8pFamPkClyD7T-cTH_KM_fJU17Fe

# HOW TO RUN A TELEGRAM BOT IN COLAB
"""

# this cell should be run only once, to install the telebot library
! pip install pytelegrambotapi

# here we create the simplest possible bot

import telebot


API_TOKEN = '1625321618:AAENq9YhPJOe-qkfRXVPHFz9dQWgvjEx2oA'
bot = telebot.TeleBot(API_TOKEN)

# Handle /start and /help
@bot.message_handler(commands=['mulai'])
def command_help(message):
    bot.reply_to(message, "Assalamualaikum wr wb  , kenalin aku  santri senior Pesantren Mutiara bangsa.  coba ketik ngaji untuk melihat list ngaji di Pesantren Mutiara Bangsa")
@bot.message_handler(regexp=['ngaji'])
def command_help(message):
    bot.reply_to(message, "coba Klik link berikut untuk ngaji https://pesantrenmutiarabangsa.com/courses/shirah-nabi-muhammad-bersama-gusbaha/")

@bot.message_handler(regexp=['kisah nabi'])
def command_help(message):
    bot.reply_to(message, "coba Klik link berikut untuk ngaji https://pesantrenmutiarabangsa.com/courses/shirah-nabi-muhammad-bersama-gusbaha/")
    
@bot.message_handler(regexp='((https?):((//)|(\\\\))+([\w\d:#@%/;$()~_?\+-=\\\.&](#!)?)*)')
def command_url(message):
    bot.reply_to(message, " Maaf  aku nggak bisa membuka link tersebut")
@bot.message_handler(regexp='seneng')
def command_url(message):
    bot.reply_to(message, "terima kasih Banyak yakk, jangan lupa ikuti sosial media kita yakk")

# and here we actually run it
bot.polling()

